import { GameList } from "@/components/elements/TopListItem";

const gamesList: GameList = {
  '7 Wonders': {
    gameArtists: 'Dimitri Chappuis, Miguel Coimbra, Etienne Hebinger, Cyril Nouvel',
    gameDesigners: 'Antoine Bauza',
    gameImageName: '7-wonders',
    gamePublisher: 'Repos Production',
    yearPublished: '2010',
  },
  '7 Wonders Duel': {
    gameArtists: 'Miguel Coimbra',
    gameDesigners: 'Antoine Bauza, Bruno Cathala',
    gameImageName: '7-wonders-duel',
    gamePublisher: 'Repos Production',
    yearPublished: '2015',
  },
  'Abandon All Artichokes': {
    gameArtists: 'Bonnie Pang',
    gameDesigners: 'Emma Larkins',
    gameImageName: 'abandon-all-artichokes',
    gamePublisher: 'Gamewright',
    yearPublished: '2020',
  },
  'Age of Steam': {
    gameArtists: `Sean Brown, Peter Dennis, Paul Niemeyer, Ian O'Toole`,
    gameDesigners: 'John Bohrer, Martin Wallace',
    gameImageName: 'age-of-steam',
    gamePublisher: 'Warfrog Games, Eagle-Gryphon Games',
    yearPublished: '2002',
  },
  'Agricola': {
    gameArtists: 'Klemens Franz',
    gameDesigners: 'Uwe Rosenberg',
    gameImageName: 'agricola',
    gamePublisher: 'Lookout Games',
    yearPublished: '2007',
  },
  'Air, Land, & Sea': {
    gameArtists: 'Valerio Buonfantino, Stephen Gibson',
    gameDesigners: 'Jon Perry',
    gameImageName: 'air-land-sea',
    gamePublisher: 'Osprey Publishing',
    yearPublished: '2019',
  },
  'Alchemists': {
    gameArtists: 'David Cochard',
    gameDesigners: 'Matúš Kotry',
    gameImageName: 'alchemists',
    gamePublisher: 'Czech Games Edition',
    yearPublished: '2014',
  },
  'Aquamarine': {
    gameArtists: 'Rory Muldoon',
    gameDesigners: 'Matthew Dunstan, Rory Muldoon',
    gameImageName: 'aquamarine',
    gamePublisher: 'Postmark Games',
    yearPublished: '2022',
  },
  'Architects of the West Kingdom': {
    gameArtists: 'Mihajlo Dimitrievski',
    gameDesigners: 'S J Macdonald, Shem Phillips',
    gameImageName: 'architects-of-the-west-kingdom',
    gamePublisher: 'Garphill Games',
    yearPublished: '2018',
  },
  'Arkham Horror: The Card Game': {
    gameArtists: 'Christopher Hosch, Marcin Jakubowski, Ignacio Bazán Lazcano, Henning Ludvigsen, Mercedes Opheim, Zoe Robinson, Evan Simonet',
    gameDesigners: 'Nate French, Maxine Juniper Newman',
    gameImageName: 'arkham-horror-lcg',
    gamePublisher: 'Fantasy Flight Games',
    yearPublished: '2016',
  },
  'Azul': {
    gameArtists: 'Philippe Guérin, Chris Quilliams',
    gameDesigners: 'Michael Kiesling',
    gameImageName: 'azul',
    gamePublisher: 'Next Move Games, Plan B Games',
    yearPublished: '2017',
  },
  'Bärenpark': {
    gameArtists: 'Klemens Franz',
    gameDesigners: 'Phil Walker-Harding',
    gameImageName: 'brenpark',
    gamePublisher: 'Lookout Games',
    yearPublished: '2017',
  },
  'Battlestar Galactica': {
    gameArtists: 'Kevin Childress, Brian Schomburg, WiL Springer',
    gameDesigners: 'Corey Konieczka',
    gameImageName: 'battlestar-galactica',
    gamePublisher: 'Fantasy Flight Games',
    yearPublished: '2008',
  },
  'Bemused': {
    gameArtists: 'Tani Pettit, Naomi Robinson',
    gameDesigners: 'Jim Felli',
    gameImageName: 'bemused',
    gamePublisher: 'Devious Weasel Games',
    yearPublished: '2017',
  },
  'Brass: Birmingham': {
    gameArtists: 'Lina Cossette, David Forest, Damien Mammoliti',
    gameDesigners: 'Gavan Brown, Matt Tolman, Martin Wallace',
    gameImageName: 'brass-birmingham',
    gamePublisher: 'Roxley',
    yearPublished: '2019',
  },
  'Brass: Lancashire': {
    gameArtists: 'Gavan Brown, Lina Cossette, Peter Dennis, David Forest',
    gameDesigners: 'Martin Wallace',
    gameImageName: 'brass-lancashire',
    gamePublisher: 'Roxley',
    yearPublished: '2007',
  },
  'By Stealth and Sea': {
    gameArtists: 'David Thompson',
    gameDesigners: 'Nicola Saggini, David Thompson',
    gameImageName: 'by-stealth-and-sea',
    gamePublisher: 'Dan Verssen Games (DVG)',
    yearPublished: '2020',
  },
  'Cacao': {
    gameArtists: 'Claus Stephan',
    gameDesigners: 'Phil Walker-Harding',
    gameImageName: 'cacao',
    gamePublisher: 'ABACUSSPIELE, G3',
    yearPublished: '2015',
  },
  'Calico': {
    gameArtists: 'Beth Sobel',
    gameDesigners: 'Kevin Russ',
    gameImageName: 'calico',
    gamePublisher: 'Flatout Games',
    yearPublished: '2020',
  },
  'Carolus Magnus | Eriantys': {
    gameArtists: 'N/A | Alessandro Costa',
    gameDesigners: 'Leo Colovini',
    gameImageName: 'eriantys',
    gamePublisher: 'Rio Grande Games | Cranio Creations',
    yearPublished: '2000 | 2021',
  },
  'Cartographers': {
    gameArtists: 'Luis Francisco, Lucas Ribeiro',
    gameDesigners: 'Jordy Adan',
    gameImageName: 'cartographers',
    gamePublisher: 'Thunderworks Games',
    yearPublished: '2019',
  },
  'Cascadia': {
    gameArtists: 'Beth Sobel',
    gameDesigners: 'Randy Flynn',
    gameImageName: 'cascadia',
    gamePublisher: 'Flatout, AEG',
    yearPublished: '2021',
  },
  'The Castles of Burgundy': {
    gameArtists: 'Julien Delval, Harald Lieske',
    gameDesigners: 'Stefan Feld',
    gameImageName: 'castles-of-burgundy',
    gamePublisher: 'alea, Ravensburger',
    yearPublished: '2011',
  },
  'Caverna: The Cave Farmers': {
    gameArtists: 'Javier González Cava, Klemens Franz',
    gameDesigners: 'Uwe Rosenberg',
    gameImageName: 'caverna',
    gamePublisher: 'Lookout Games',
    yearPublished: '2013',
  },
  'Charterstone': {
    gameArtists: 'Lina Cossette, David Forest',
    gameDesigners: 'Jamey Stegmaier',
    gameImageName: 'charterstone',
    gamePublisher: 'Stonemaier Games',
    yearPublished: '2017',
  },
  'Clank!: Legacy – Acquisitions Incorporated': {
    gameArtists: 'Clay Brooks, Anika Burrell, Derek Herring, Raul Ramos, Nate Storm, Alain Viesca',
    gameDesigners: 'Andy Clautice, Paul Dennen',
    gameImageName: 'clank-legacy',
    gamePublisher: 'Renegade',
    yearPublished: '2019',
  },
  'Codenames': {
    gameArtists: 'Stéphane Gantiez, Tomáš Kučerovský, Filip Murmak',
    gameDesigners: 'Vlaada Chvátil',
    gameImageName: 'codenames',
    gamePublisher: 'Czech Games Edition',
    yearPublished: '2015',
  },
  'Cosmic Frog': {
    gameArtists: 'Tim Barton, Jim Felli, Chad Hoverter, Tani Pettit, Naomi Robinson',
    gameDesigners: 'Jim Felli',
    gameImageName: 'cosmic-frog',
    gamePublisher: 'Devious Weasel Games',
    yearPublished: '2020',
  },
  'Crokinole': {
    gameImageName: 'crokinole',
    gamePublisher: '(Public Domain)',
    yearPublished: '1876',
  },
  'Dice Throne': {
    gameArtists: 'Gavan Brown, Manny Trembley',
    gameDesigners: 'Nate Chatellier, Manny Trembley',
    gameImageName: 'dice-throne',
    gamePublisher: 'Roxley',
    yearPublished: '2018',
  },
  "Dinosaur Island: Rawr 'n Write": {
    gameArtists: 'Kwanchai Moriya, Andrew Thompson',
    gameDesigners: 'Brian Lewis, David McGregor, Marissa Misura',
    gameImageName: 'dinosaur-island-rawr-n-write',
    gamePublisher: 'Pandasaurus Games',
    yearPublished: '2021',
  },
  'Dominion': {
    gameArtists: 'Matthias Catrein, Julien Delval, Tomasz Jedruszek, Ryan Laukat, Harald Lieske, Michael Menzel, Marcel-André Casasola Merkle, Claus Stephan, Christof Tisch',
    gameDesigners: 'Donald X. Vaccarino',
    gameImageName: 'dominion',
    gamePublisher: 'Rio Grande Games',
    yearPublished: '2008',
  },
  'Draftosaurus': {
    gameArtists: 'Jiahui Eva Gao, Vipin Alex Jacob, Roman Kucharski, TANSAN Inc.',
    gameDesigners: 'Antoine Bauza, Corentin Lebrat, Ludovic Maublanc, Théo Rivière',
    gameImageName: 'draftosaurus',
    gamePublisher: 'Ankama',
    yearPublished: '2019',
  },
  'Dûhr: The Lesser Houses': {
    gameArtists: 'Reza Afshar, Jonathan Guzi',
    gameDesigners: 'Jim Felli',
    gameImageName: 'dhr-the-lesser-houses',
    gamePublisher: 'Devious Weasel Games',
    yearPublished: '2018',
  },
  'Dungeon Petz': {
    gameArtists: 'David Cochard',
    gameDesigners: 'Vlaada Chvátil',
    gameImageName: 'dungeon-petz',
    gamePublisher: 'Czech Games Edition',
    yearPublished: '2011',
  },
  'Euphoria: Build a Better Dystopia': {
    gameArtists: 'Jacqui Davis',
    gameDesigners: 'Jamey Stegmaier, Alan Stone',
    gameImageName: 'euphoria',
    gamePublisher: 'Stonemaier Games',
    yearPublished: '2013',
  },
  'Fantastic Factories': {
    gameArtists: 'Joseph Z Chen',
    gameDesigners: 'Joseph Chen, Justin Fauilkner',
    gameImageName: 'fantastic-factories',
    gamePublisher: 'Metafactory Games, Deep Water Games',
    yearPublished: '2019',
  },
  'A Feast for Odin': {
    gameArtists: 'Dennis Lohausen',
    gameDesigners: 'Uwe Rosenberg',
    gameImageName: 'feast-for-odin',
    gamePublisher: 'Feuerland Spiele',
    yearPublished: '2016',
  },
  'Fields of Arle': {
    gameArtists: 'Dennis Lohausen',
    gameDesigners: 'Uwe Rosenberg',
    gameImageName: 'fields-of-arle',
    gamePublisher: 'Feuerland Spiele',
    yearPublished: '2014',
  },
  'Five Tribes': {
    gameArtists: 'Clément Masson',
    gameDesigners: 'Bruno Cathala',
    gameImageName: 'five-tribes',
    gamePublisher: 'Days of Wonder',
    yearPublished: '2014',
  },
  'Fleet': {
    gameArtists: 'Eric J. Carter',
    gameDesigners: 'Ben Pinchback, Matt Riddle',
    gameImageName: 'fleet',
    gamePublisher: 'Eagle-Gryphon Games',
    yearPublished: '2012',
  },
  'Fleet: The Dice Game': {
    gameArtists: 'Marius Janusonis, Nolan Nasser',
    gameDesigners: 'Ben Pinchback, Matt Riddle',
    gameImageName: 'fleet-the-dice-game',
    gamePublisher: 'Eagle-Gryphon Games',
    yearPublished: '2018',
  },
  'The Fox Experiment': {
    gameArtists: 'Joe Shawcross',
    gameDesigners: 'Elizabeth Hargrave, Jeff Fraser',
    gameImageName: 'fox-experiment',
    gamePublisher: 'Pandasaurus Games',
    yearPublished: '2023',
  },
  'Galaxy Trucker': {
    gameArtists: 'Tomáš Kučerovský, Radim Pech',
    gameDesigners: 'Vlaada Chvátil',
    gameImageName: 'galaxy-trucker',
    gamePublisher: 'Czech Games Edition',
    yearPublished: '2007',
  },
  'Gaslands: Refuelled': {
    gameArtists: 'Mike Hutchinson, David Auden Nash, Martin Pique',
    gameDesigners: 'Mike Hutchinson',
    gameImageName: 'gaslands',
    gamePublisher: 'Osprey Publishing',
    imageExtension: 'jpg',
    yearPublished: '2019',
  },
  'Ghost Stories': {
    gameArtists: 'Pierô',
    gameDesigners: 'Antoine Bauza',
    gameImageName: 'ghost-stories',
    gamePublisher: 'Repos Production',
    yearPublished: '2008',
  },
  'Gloomhaven: Jaws of the Lion': {
    gameArtists: 'Francesca Baerald, David Demaret, Alexandr Elichev',
    gameDesigners: 'Isaac Childress',
    gameImageName: 'gloomhaven-jaws-of-the-lion',
    gamePublisher: 'Cephalofair Games',
    yearPublished: '2020',
  },
  'Gizmos': {
    gameArtists: 'Hannah Cardoso, Júlia Ferrari, Giovanna BC Guimarães, Mathieu Harlaut, Saeed Jalabi',
    gameDesigners: 'Phil Walker-Harding',
    gameImageName: 'gizmos',
    gamePublisher: 'CMON Global Limited',
    yearPublished: '2018',
  },
  "Hadrian's Wall": {
    gameArtists: 'Sam Phillips',
    gameDesigners: 'Bobby Hill',
    gameImageName: 'hadrians-wall',
    gamePublisher: 'Garphill Games',
    yearPublished: '2021',
  },
  'Hanabi': {
    gameArtists: 'Antoine Bauza, Gérald Guerlais, Albertine Ralenti',
    gameDesigners: 'Antoine Bauza',
    gameImageName: 'hanabi',
    gamePublisher: 'ABACUSSPIELE, Cocktail Games',
    yearPublished: '2010',
  },
  'Hoplomachus: Remastered': {
    gameArtists: 'Yoann Boissonnet, Anthony LeTourneau, Federico Pompili',
    gameDesigners: 'Adam Carlson, Josh J. Carlson, Logan Giannini',
    gameImageName: 'hoplomachus-remastered',
    gamePublisher: 'Chip Theory Games',
    yearPublished: '2023',
  },
  'Imhotep': {
    gameArtists: 'Miguel Coimbra, Michaela Kienle',
    gameDesigners: 'Phil Walker-Harding',
    gameImageName: 'imhotep',
    gamePublisher: 'KOSMOS',
    yearPublished: '2016',
  },
  'Imperial Settlers: Empires of the North': {
    gameArtists: 'Grzegorz Bobrowski, Roman Kucharski',
    gameDesigners: 'Joanna Kijanka, Ignacy Trzewiczek',
    gameImageName: 'imperial-settlers-empires-of-the-north',
    gamePublisher: 'Portal Games',
    yearPublished: '2019',
  },
  'Imperium: Classics | Legends': {
    gameArtists: 'Mihajlo Dimitrievski',
    gameDesigners: 'Nigel Buckle, Dávid Turczi',
    gameImageName: 'imperium-classics-legends',
    gamePublisher: 'Osprey Games',
    yearPublished: '2021',
  },
  'Jaipur': {
    gameArtists: 'Vincent Dutrait, Alexandre Roche',
    gameDesigners: 'Sébastien Pauchon',
    gameImageName: 'jaipur',
    gamePublisher: 'GameWorks SàRL, Space Cowboys',
    yearPublished: '2009',
  },
  'Kingdomino Duel': {
    gameArtists: 'Cyril Bouquet',
    gameDesigners: 'Bruno Cathala, Ludovic Maublanc',
    gameImageName: 'kingdomino-duel',
    gamePublisher: 'Blue Orange Games',
    yearPublished: '2019',
  },
  'Le Havre': {
    gameArtists: 'Klemens Franz',
    gameDesigners: 'Uwe Rosenberg',
    gameImageName: 'le-havre',
    gamePublisher: 'Lookout Games',
    yearPublished: '2008',
  },
  'Legendary: A Marvel Deck Building Game': {
    gameArtists: 'Julius Abrea, Will Conrad, Bien Flores, Katrina Mae Hao, Ray Anthony Height, Tony Kordos, The Marvel Bullpen, Jay David Ramos, Nigel Raynor, Kevin Sharpe, Brian “Tots” Valerz',
    gameDesigners: 'Devin Low',
    gameImageName: 'legendary-marvel',
    gamePublisher: 'Upper Deck',
    yearPublished: '2012',
  },
  'The Lord of the Rings Trading Card Game': {
    gameDesigners: 'Chuck Kallenbach, Tom Lischke, Mike Reynolds',
    gameImageName: 'lotr-tcg',
    gamePublisher: 'Decipher',
    yearPublished: '2001',
  },
  'Lost Cities': {
    gameArtists: 'Vincent Dutrait, Michaela Kienle, Anke Pohl, Thilo Rick',
    gameDesigners: 'Reiner Knizia',
    gameImageName: 'lost-cities',
    gamePublisher: 'KOSMOS',
    yearPublished: '1999',
  },
  'Lost Ruins of Arnak': {
    gameArtists: 'Ondřej Hrdina, Jiří Kůs, Jakub Politzer, František Sedláček, Milan Vavroň',
    gameDesigners: 'Elwen, Mín',
    gameImageName: 'lost-ruins-of-arnak',
    gamePublisher: 'Czech Games Edition',
    yearPublished: '2020',
  },
  'Mage Knight Board Game': {
    gameArtists: 'J. Lonnee, Chris Raimo, Milan Vavroň',
    gameDesigners: 'Vlaada Chvátil',
    gameImageName: 'mage-knight-board-game',
    gamePublisher: 'WizKids',
    yearPublished: '2011',
  },
  'Mariposas': {
    gameArtists: 'Matt Paquette & Co., Indi Maverick',
    gameDesigners: 'Elizabeth Hargrave',
    gameImageName: 'mariposas',
    gamePublisher: 'Alderac Entertainment Group',
    yearPublished: '2020',
  },
  'Marvel Champions: The Card Game': {
    gameDesigners: 'Michael Boggs',
    gameImageName: 'marvel-champions',
    gamePublisher: 'Fantasy Flight Games',
    yearPublished: '2019',
  },
  'Marvel Dice Throne': {
    gameArtists: 'Damien Mammoliti, Manny Trembley',
    gameDesigners: 'Gavan Brown, Nate Chatellier, Manny Trembley',
    gameImageName: 'marvel-dice-throne',
    gamePublisher: 'The Op, Roxley',
    yearPublished: '2022',
  },
  'The Mirroring of Mary King': {
    gameArtists: 'Naomi Robinson',
    gameDesigners: 'Jim Felli',
    gameImageName: 'mirroring-of-mary-king',
    gamePublisher: 'Devious Weasel Games',
    yearPublished: '2022',
  },
  'NMBR 9': {
    gameArtists: 'Fiore GmbH',
    gameDesigners: 'Peter Wichmann',
    gameImageName: 'nmbr-9',
    gamePublisher: 'Z-Man Games',
    yearPublished: '2017',
  },
  'Onitama': {
    gameArtists: 'Jun Kondo, Mariusz Szmerdt',
    gameDesigners: 'Shimpei Sato',
    gameImageName: 'onitama',
    gamePublisher: 'conception',
    yearPublished: '2014',
  },
  'Paladins of the West Kingdom': {
    gameArtists: 'Mihajlo Dimitrievski',
    gameDesigners: 'S J Macdonald, Shem Phillips',
    gameImageName: 'paladins-of-the-west-kingdom',
    gamePublisher: 'Garphill Games, Renegade Game Studios',
    yearPublished: '2019',
  },
  'Patchwork': {
    gameArtists: 'Klemens Franz, Rex Lee, Jolanta Lendzioszek, Gru Tsow',
    gameDesigners: 'Uwe Rosenberg',
    gameImageName: 'patchwork',
    gamePublisher: 'Lookout Games',
    yearPublished: '2014',
  },
  'Piepmatz': {
    gameArtists: 'Klemens Franz, Mike Langman',
    gameDesigners: 'Ben Pinchback, Matt Riddle',
    gameImageName: 'piepmatz',
    gamePublisher: 'ASS Altenburger Spielkarten, Funforge, Hobby Game Mall, Lookout Games',
    yearPublished: '2018',
  },
  'Pokémon Trading Card Game': {
    gameArtists: 'Koichi Ooyama, Hironobu Yoshida',
    gameDesigners: 'Takumi Akabane, Tsunekaz Ishihara',
    gameImageName: 'pokemon-tcg',
    gamePublisher: 'The Pokémon Company',
    yearPublished: '1996',
  },
  'Puzzle Dungeon': {
    gameArtists: 'Brian Garber',
    gameDesigners: 'Brian Garber',
    gameImageName: 'puzzle-dungeon',
    gamePublisher: '(Self-Published)',
    yearPublished: '2019',
  },
  'The Quacks of Quedlinburg': {
    gameArtists: 'Dennis Lohausen, Wolfgang Warsch',
    gameDesigners: 'Wolfgang Warsch',
    gameImageName: 'quacks-of-quedlinburg',
    gamePublisher: 'Schmidt Spiele',
    yearPublished: '2018',
  },
  'Radlands': {
    gameArtists: 'Lina Cossette, Damien Mammoliti, Manny Trembley',
    gameDesigners: 'Daniel Piechnick',
    gameImageName: 'radlands',
    gamePublisher: 'Roxley',
    yearPublished: '2021',
  },
  'Raiders of the North Sea': {
    gameArtists: 'Mihajlo Dimitrievski',
    gameDesigners: 'Shem Phillips',
    gameImageName: 'raiders-of-the-north-sea',
    gamePublisher: 'Garphill Games',
    yearPublished: '2015',
  },
  'Raiders of Scythia': {
    gameArtists: 'Sam Phillips',
    gameDesigners: 'Shem Phillips',
    gameImageName: 'raiders-of-scythia',
    gamePublisher: 'Garphill Games',
    yearPublished: '2020',
  },
  'Railways of the World': {
    gameArtists: 'Kurt Miller, Paul Niemeyer, David Oram',
    gameDesigners: 'Glenn Drover, Martin Wallace',
    gameImageName: 'railway-of-the-world',
    gamePublisher: 'Eagle-Gryphon Games, Winsome Games',
    yearPublished: '2005',
  },
  'Raptor': {
    gameArtists: 'Vincent Dutrait',
    gameDesigners: 'Bruno Cathala, Bruno Faidutti',
    gameImageName: 'raptor',
    gamePublisher: 'Matagot',
    yearPublished: '2015',
  },
  'The Red Cathedral': {
    gameArtists: 'Chema Román, Pedro Soto',
    gameDesigners: 'Isra C., Shei S.',
    gameImageName: 'red-cathedral',
    gamePublisher: 'Devir',
    yearPublished: '2020',
  },
  'Red Rising': {
    gameArtists: 'Miles Bensky, Jacqui Davis, Justin Wong',
    gameDesigners: 'Jamey Stegmaier',
    gameImageName: 'red-rising',
    gamePublisher: 'Stonemaier Games',
    yearPublished: '2021',
  },
  'Resist!': {
    gameArtists: 'Albert Monteys',
    gameDesigners: 'Trevor Benjamin, Roger Tankersley, David Thompson',
    gameImageName: 'resist',
    gamePublisher: 'Salt & Pepper Games',
    yearPublished: '2022',
  },
  'Rolling Realms': {
    gameArtists: 'Miles Bensky, Marius Petrescu',
    gameDesigners: 'Jamey Stegmaier',
    gameImageName: 'rolling-realms',
    gamePublisher: 'Stonemaier Games',
    yearPublished: '2021',
  },
  'Scythe': {
    gameArtists: 'Jakub Rozalski',
    gameDesigners: 'Jamey Stegmaier',
    gameImageName: 'scythe',
    gamePublisher: 'Stonemaier Games',
    yearPublished: '2016',
  },
  'Shadows of Malice': {
    gameArtists: 'Jim Felli',
    gameDesigners: 'Jim Felli',
    gameImageName: 'shadows-of-malice',
    gamePublisher: 'Devious Weasel Games',
    yearPublished: '2014',
  },
  'Shards of Infinity': {
    gameArtists: 'Aaron Nakahara',
    gameDesigners: 'Gary Arant, Justin Gary',
    gameImageName: 'shards-of-infinity',
    gamePublisher: 'Stone Blade Entertainment, Ultra PRO',
    yearPublished: '2018',
  },
  'Silver & Gold': {
    gameArtists: 'Oliver Freudenreich',
    gameDesigners: 'Phil Walker-Harding',
    gameImageName: 'silver-and-gold',
    gamePublisher: 'Nürnberger-Spielkarten-Verlag',
    yearPublished: '2019',
  },
  'Sniper Elite: The Board Game': {
    gameArtists: 'Jose David Lanza Cebrian, Edouard Grould, Ed Savage',
    gameDesigners: 'Roger Tankersley, David Thompson',
    gameImageName: 'sniper-elite-the-board-game',
    gamePublisher: 'Rebellion Unplugged',
    yearPublished: '2022',
  },
  'Sobek: 2 Players': {
    gameArtists: 'Xavier Gueniffey Durin',
    gameDesigners: 'Bruno Cathala, Sébastien Pauchon',
    gameImageName: 'sobek-2-players',
    gamePublisher: 'Catch Up Games',
    yearPublished: '2021',
  },
  'Spirit Island': {
    gameArtists: 'Jason Behnke, Loïc Berger, Loïc Billiau, Kat G Birmelin, Cari Corene, Lucas Durham, Rocky Hammer, Sydni Kruger, Nolan Nasser, Jorge Ramos, Adam Rebottaro, Moro Rogers, Graham Sternberg, Shane Tyree, Joshua Wright (I)',
    gameDesigners: 'R. Eric Reuss',
    gameImageName: 'spirit-island',
    gamePublisher: 'Greater Than Games, LLC',
    yearPublished: '2017',
  },
  'Space Alert': {
    gameArtists: 'Radim Pech, Milan Vavroň',
    gameDesigners: 'Vlaada Chvátil',
    gameImageName: 'space-alert',
    gamePublisher: 'Czech Games Edition',
    yearPublished: '2008',
  },
  'Splendor Duel': {
    gameArtists: 'Davide Tosello',
    gameDesigners: 'Marc André, Bruno Cathala',
    gameImageName: 'splendor-duel',
    gamePublisher: 'Space Cowboys',
    yearPublished: '2022',
  },
  'Sprawlopolis': {
    gameArtists: 'Loïc Billiau, Dalton Cara, Danny Devine',
    gameDesigners: 'Steven Aramini, Danny Devine, Paul Kluka',
    gameImageName: 'sprawlopolis',
    gamePublisher: 'Button Shy',
    yearPublished: '2018',
  },
  'Star Wars: Destiny': {
    gameArtists: 'Lucas Durham, Vlad Ricean',
    gameDesigners: 'Corey Konieczka, Lukas Litzsinger',
    gameImageName: 'star-wars-destiny',
    gamePublisher: 'Fantasy Flight Games',
    yearPublished: '2016',
  },
  'Steam': {
    gameArtists: 'John Austin, Jared Blando, Craig Hamilton, Christopher Moeller',
    gameDesigners: 'Martin Wallace',
    gameImageName: 'steam',
    gamePublisher: 'Mayfair Games',
    yearPublished: '2009',
  },
  'Stellar': {
    gameArtists: 'Tim Barton, Janos Orban',
    gameDesigners: 'Ben Pinchback, Matt Riddle',
    gameImageName: 'stellar',
    gamePublisher: 'Renegade Game Studios',
    yearPublished: '2020',
  },
  'A Study in Emerald': {
    gameArtists: 'Geof Banyard, Peter Dennis, Anne Stokes',
    gameDesigners: 'Martin Wallace',
    gameImageName: 'study-in-emerald',
    gamePublisher: 'Treefrog Games',
    yearPublished: '2013',
  },
  'Summoner Wars: Master Set': {
    gameArtists: 'JJ Ariosa, Gary Simpson',
    gameDesigners: 'Colby Dauch',
    gameImageName: 'summoner-wars',
    gamePublisher: 'Plaid Hat Games',
    yearPublished: '2011',
  },
  'Super-Skill Pinball: 4-Cade': {
    gameArtists: 'Gong Studios',
    gameDesigners: 'Geoff Engelstein',
    gameImageName: 'super-skill-pinball-4-cade',
    gamePublisher: 'WizKids',
    yearPublished: '2020',
  },
  'Sushi Go Party!': {
    gameArtists: 'Nan Rangsima',
    gameDesigners: 'Phil Walker-Harding',
    gameImageName: 'sushi-go-party',
    gamePublisher: 'Gamewright',
    yearPublished: '2016',
  },
  'Switch & Signal': {
    gameArtists: 'Claus Stephan, Antje Stephan',
    gameDesigners: 'David Thompson',
    gameImageName: 'switch-signal',
    gamePublisher: 'KOSMOS',
    yearPublished: '2020',
  },
  'Takenoko': {
    gameArtists: 'Nicolas Fructus, Picksel, Yuio',
    gameDesigners: 'Antoine Bauza',
    gameImageName: 'takenoko',
    gamePublisher: 'Bombyx, Matagot',
    yearPublished: '2011',
  },
  'Tapestry': {
    gameArtists: 'Andrew Bosley, Rom Brown',
    gameDesigners: 'Jamey Stegmaier',
    gameImageName: 'tapestry',
    gamePublisher: 'Stonemaier Games',
    yearPublished: '2019',
  },
  'Targi': {
    gameArtists: 'Taira Akitsu, Franz Vohwinkel',
    gameDesigners: 'Andreas Steiger',
    gameImageName: 'targi',
    gamePublisher: 'KOSMOS',
    yearPublished: '2012',
  },
  'Terraforming Mars: Ares Expedition': {
    gameArtists: 'William Bricker, Sydney Engelstein, Jacob Fryxelius, Garrett Kaida, Nick Little, Nio Mendoza, Justine Nortjé, Naomi Robinson, Andrei Stef',
    gameDesigners: 'Sydney Engelstein, Jacob Fryxelius, Nick Little',
    gameImageName: 'terraforming-mars-ares-expedition',
    gamePublisher: 'FryxGames, Stronghold Games',
    yearPublished: '2021',
  },
  'That Time You Killed Me': {
    gameArtists: 'Jor Ros',
    gameDesigners: 'Peter C. Hayward',
    gameImageName: 'that-time-you-killed-me',
    gamePublisher: 'Pandasaurus Games',
    yearPublished: '2021',
  },
  'Three Sisters': {
    gameArtists: 'Marlies Barends, Beth Sobel',
    gameDesigners: 'Ben Pinchback, Matt Riddle',
    gameImageName: 'three-sisters',
    gamePublisher: 'Motor City Gameworks',
    yearPublished: '2022',
  },
  'Through the Ages: A New Story of Civilization': {
    gameArtists: 'Filip Murmak, Radim Pech, Jakub Politzer, Milan Vavroň',
    gameDesigners: 'Vlaada Chvátil',
    gameImageName: 'through-ages-new-story-civilization',
    gamePublisher: 'Czech Games Edition',
    yearPublished: '2015',
  },
  'Ticket to Ride: Europe': {
    gameArtists: 'Cyrille Daujean, Julien Delval',
    gameDesigners: 'Alan R. Moon',
    gameImageName: 'ticket-to-ride-europe',
    gamePublisher: 'Days of Wonder',
    yearPublished: '2005',
  },
  'Tussie Mussie': {
    gameArtists: 'Loïc Billiau, Karolina Jędrzejak, Zarina Karapetyan, Beth Sobel',
    gameDesigners: 'Elizabeth Hargrave',
    gameImageName: 'tussie-mussie',
    gamePublisher: 'Button Shy',
    yearPublished: '2019',
  },
  'Undaunted: Stalingrad': {
    gameArtists: 'Roland MacDonald',
    gameDesigners: 'Trevor Benjamin, David Thompson',
    gameImageName: 'undaunted-stalingrad',
    gamePublisher: 'Osprey Games',
    yearPublished: '2022',
  },
  'Vagrantsong': {
    gameArtists: 'Nguyen Mai Diem',
    gameDesigners: 'Matt Carter, Justin Gibbs, Kyle Rowan',
    gameImageName: 'vagrantsong',
    gamePublisher: 'Wyrd Miniatures',
    yearPublished: '2022',
  },
  'Viscounts of the West Kingdom': {
    gameArtists: 'Mihajlo Dimitrievski',
    gameDesigners: 'S J Macdonald, Shem Phillips',
    gameImageName: 'viscounts-of-the-west-kingdom',
    gamePublisher: 'Garphill Games',
    yearPublished: '2020',
  },
  'Viticulture Essential Edition': {
    gameArtists: 'Jacqui Davis, David Montgomery, Beth Sobel',
    gameDesigners: 'Jamey Stegmaier, Alan Stone',
    gameImageName: 'viticulture-ee',
    gamePublisher: 'Stonemaier Games',
    yearPublished: '2015',
  },
  'War Chest': {
    gameArtists: 'Brigette Indelicato',
    gameDesigners: 'Trevor Benjamin, David Thompson',
    gameImageName: 'war-chest',
    gamePublisher: 'Alderac Entertainment Group',
    yearPublished: '2018',
  },
  'Wasteland Express Delivery Service': {
    gameArtists: 'Riccardo Burchielli, Josh Cappel, Jason D. Kingsley',
    gameDesigners: 'Jonathan Gilmour, Ben Pinchback, Matt Riddle',
    gameImageName: 'wasteland-express-delivery-service',
    gamePublisher: 'Asmodee, Asmodee China, Pandasaurus Games',
    yearPublished: '2017',
  },
  'Watergate': {
    gameArtists: 'Klemens Franz, Viktor Kobilke',
    gameDesigners: 'Matthias Cramer',
    gameImageName: 'watergate',
    gamePublisher: 'Capstone Games',
    yearPublished: '2019',
  },
  'Wayfarers of the South Tigris': {
    gameArtists: 'Mihajlo Dimitrievski',
    gameDesigners: 'S J Macdonald, Shem Phillips',
    gameImageName: 'wayfarers-of-the-south-tigris',
    gamePublisher: 'Garphill Games',
    yearPublished: '2022',
  },
  'Wingspan': {
    gameArtists: 'Ana Maria Martinez Jaramillo, Natalia Rojas, Beth Sobel',
    gameDesigners: 'Elizabeth Hargrave',
    gameImageName: 'wingspan',
    gamePublisher: 'Stonemaier Games',
    yearPublished: '2019',
  },
  'Wok and Roll': {
    gameDesigners: 'Daryl Chow',
    gameImageName: 'wok-and-roll',
    gamePublisher: 'Origame',
    yearPublished: '2020',
  },
  "Wonderland's War": {
    gameArtists: 'Manny Trembley',
    gameDesigners: 'Tim Eisner, Ben Eisner, Ian Moss',
    gameImageName: 'wonderlands-war',
    gamePublisher: 'Druid City Games',
    yearPublished: '2022',
  },
  'Zimby Mojo': {
    gameArtists: 'Jim Felli, Tani Pettit, Naomi Robinson',
    gameDesigners: 'Jim Felli',
    gameImageName: 'zimby-mojo',
    gamePublisher: 'Devious Weasel Games',
    yearPublished: '2016',
  },
}

export default gamesList;
