import { GameList } from "@/components/elements/TopListItem";

const gamesList: GameList = {
  '7 Wonders Duel': {
    gameArtists: 'Miguel Coimbra',
    gameDesigners: 'Antoine Bauza, Bruno Cathala',
    gameImageName: '7-wonders-duel',
    gamePublisher: 'Repos Production',
    yearPublished: '2015',
  },
  'Age of Steam': {
    gameArtists: `Sean Brown, Peter Dennis, Paul Niemeyer, Ian O'Toole`,
    gameDesigners: 'John Bohrer, Martin Wallace',
    gameImageName: 'age-of-steam',
    gamePublisher: 'Warfrog Games, Eagle-Gryphon Games',
    yearPublished: '2002',
  },
  'Agricola': {
    gameArtists: 'Klemens Franz',
    gameDesigners: 'Uwe Rosenberg',
    gameImageName: 'agricola',
    gamePublisher: 'Lookout Games',
    yearPublished: '2007',
  },
  'Air, Land, & Sea': {
    gameArtists: 'Valerio Buonfantino, Stephen Gibson',
    gameDesigners: 'Jon Perry',
    gameImageName: 'air-land-sea',
    gamePublisher: 'Osprey Publishing',
    yearPublished: '2019',
  },
  'Alchemists': {
    gameArtists: 'David Cochard',
    gameDesigners: 'Matúš Kotry',
    gameImageName: 'alchemists',
    gamePublisher: 'Czech Games Edition',
    yearPublished: '2014',
  },
  'Architects of the West Kingdom': {
    gameArtists: 'Mihajlo Dimitrievski',
    gameDesigners: 'S J Macdonald, Shem Phillips',
    gameImageName: 'architects-of-the-west-kingdom',
    gamePublisher: 'Garphill Games',
    yearPublished: '2018',
  },
  'Azul': {
    gameArtists: 'Philippe Guérin, Chris Quilliams',
    gameDesigners: 'Michael Kiesling',
    gameImageName: 'azul',
    gamePublisher: 'Next Move Games, Plan B Games',
    yearPublished: '2017',
  },
  'Bemused': {
    gameArtists: 'Tani Pettit, Naomi Robinson',
    gameDesigners: 'Jim Felli',
    gameImageName: 'bemused',
    gamePublisher: 'Devious Weasel Games',
    yearPublished: '2017',
  },
  'Brass: Birmingham': {
    gameArtists: 'Lina Cossette, David Forest, Damien Mammoliti',
    gameDesigners: 'Gavan Brown, Matt Tolman, Martin Wallace',
    gameImageName: 'brass-birmingham',
    gamePublisher: 'Roxley',
    yearPublished: '2019',
  },
  'Brass: Lancashire': {
    gameArtists: 'Gavan Brown, Lina Cossette, Peter Dennis, David Forest',
    gameDesigners: 'Martin Wallace',
    gameImageName: 'brass-lancashire',
    gamePublisher: 'Roxley',
    yearPublished: '2007',
  },
  'By Stealth and Sea': {
    gameArtists: 'David Thompson',
    gameDesigners: 'Nicola Saggini, David Thompson',
    gameImageName: 'by-stealth-and-sea',
    gamePublisher: 'Dan Verssen Games (DVG)',
    yearPublished: '2020',
  },
  'Carolus Magnus | Eriantys': {
    gameArtists: 'N/A | Alessandro Costa',
    gameDesigners: 'Leo Colovini',
    gameImageName: 'eriantys',
    gamePublisher: 'Rio Grande Games | Cranio Creations',
    yearPublished: '2000 | 2021',
  },
  'Caverna: The Cave Farmers': {
    gameArtists: 'Javier González Cava, Klemens Franz',
    gameDesigners: 'Uwe Rosenberg',
    gameImageName: 'caverna',
    gamePublisher: 'Lookout Games',
    yearPublished: '2013',
  },
  'Codenames': {
    gameArtists: 'Stéphane Gantiez, Tomáš Kučerovský, Filip Murmak',
    gameDesigners: 'Vlaada Chvátil',
    gameImageName: 'codenames',
    gamePublisher: 'Czech Games Edition',
    yearPublished: '2015',
  },
  'Cosmic Frog': {
    gameArtists: 'Tim Barton, Jim Felli, Chad Hoverter, Tani Pettit, Naomi Robinson',
    gameDesigners: 'Jim Felli',
    gameImageName: 'cosmic-frog',
    gamePublisher: 'Devious Weasel Games',
    yearPublished: '2020',
  },
  'Crokinole': {
    gameImageName: 'crokinole',
    gamePublisher: '(Public Domain)',
    yearPublished: '1876',
  },
  'Dominion': {
    gameArtists: 'Matthias Catrein, Julien Delval, Tomasz Jedruszek, Ryan Laukat, Harald Lieske, Michael Menzel, Marcel-André Casasola Merkle, Claus Stephan, Christof Tisch',
    gameDesigners: 'Donald X. Vaccarino',
    gameImageName: 'dominion',
    gamePublisher: 'Rio Grande Games',
    yearPublished: '2008',
  },
  'Dûhr: The Lesser Houses': {
    gameArtists: 'Reza Afshar, Jonathan Guzi',
    gameDesigners: 'Jim Felli',
    gameImageName: 'dhr-the-lesser-houses',
    gamePublisher: 'Devious Weasel Games',
    yearPublished: '2018',
  },
  'Dungeon Petz': {
    gameArtists: 'David Cochard',
    gameDesigners: 'Vlaada Chvátil',
    gameImageName: 'dungeon-petz',
    gamePublisher: 'Czech Games Edition',
    yearPublished: '2011',
  },
  'A Feast for Odin': {
    gameArtists: 'Dennis Lohausen',
    gameDesigners: 'Uwe Rosenberg',
    gameImageName: 'feast-for-odin',
    gamePublisher: 'Feuerland Spiele',
    yearPublished: '2016',
  },
  'Fields of Arle': {
    gameArtists: 'Dennis Lohausen',
    gameDesigners: 'Uwe Rosenberg',
    gameImageName: 'fields-of-arle',
    gamePublisher: 'Feuerland Spiele',
    yearPublished: '2014',
  },
  'Galaxy Trucker': {
    gameArtists: 'Tomáš Kučerovský, Radim Pech',
    gameDesigners: 'Vlaada Chvátil',
    gameImageName: 'galaxy-trucker',
    gamePublisher: 'Czech Games Edition',
    yearPublished: '2007',
  },
  'Gaslands: Refuelled': {
    gameArtists: 'Mike Hutchinson, David Auden Nash, Martin Pique',
    gameDesigners: 'Mike Hutchinson',
    gameImageName: 'gaslands',
    gamePublisher: 'Osprey Publishing',
    imageExtension: 'jpg',
    yearPublished: '2019',
  },
  'Jaipur': {
    gameArtists: 'Vincent Dutrait, Alexandre Roche',
    gameDesigners: 'Sébastien Pauchon',
    gameImageName: 'jaipur',
    gamePublisher: 'GameWorks SàRL, Space Cowboys',
    yearPublished: '2009',
  },
  'Kingdomino Duel': {
    gameArtists: 'Cyril Bouquet',
    gameDesigners: 'Bruno Cathala, Ludovic Maublanc',
    gameImageName: 'kingdomino-duel',
    gamePublisher: 'Blue Orange Games',
    yearPublished: '2019',
  },
  'Le Havre': {
    gameArtists: 'Klemens Franz',
    gameDesigners: 'Uwe Rosenberg',
    gameImageName: 'le-havre',
    gamePublisher: 'Lookout Games',
    yearPublished: '2008',
  },
  'Lost Cities': {
    gameArtists: 'Vincent Dutrait, Michaela Kienle, Anke Pohl, Thilo Rick',
    gameDesigners: 'Reiner Knizia',
    gameImageName: 'lost-cities',
    gamePublisher: 'KOSMOS',
    yearPublished: '1999',
  },
  'Mage Knight Board Game': {
    gameArtists: 'J. Lonnee, Chris Raimo, Milan Vavroň',
    gameDesigners: 'Vlaada Chvátil',
    gameImageName: 'mage-knight-board-game',
    gamePublisher: 'WizKids',
    yearPublished: '2011',
  },
  'Marvel Champions: The Card Game': {
    gameDesigners: 'Michael Boggs',
    gameImageName: 'marvel-champions',
    gamePublisher: 'Fantasy Flight Games',
    yearPublished: '2019',
  },
  'Marvel Dice Throne': {
    gameArtists: 'Damien Mammoliti, Manny Trembley',
    gameDesigners: 'Gavan Brown, Nate Chatellier, Manny Trembley',
    gameImageName: 'marvel-dice-throne',
    gamePublisher: 'The Op, Roxley',
    yearPublished: '2022',
  },
  'The Mirroring of Mary King': {
    gameArtists: 'Naomi Robinson',
    gameDesigners: 'Jim Felli',
    gameImageName: 'mirroring-of-mary-king',
    gamePublisher: 'Devious Weasel Games',
    yearPublished: '2022',
  },
  'Onitama': {
    gameArtists: 'Jun Kondo, Mariusz Szmerdt',
    gameDesigners: 'Shimpei Sato',
    gameImageName: 'onitama',
    gamePublisher: 'conception',
    yearPublished: '2014',
  },
  'Paladins of the West Kingdom': {
    gameArtists: 'Mihajlo Dimitrievski',
    gameDesigners: 'S J Macdonald, Shem Phillips',
    gameImageName: 'paladins-of-the-west-kingdom',
    gamePublisher: 'Garphill Games, Renegade Game Studios',
    yearPublished: '2019',
  },
  'Patchwork': {
    gameArtists: 'Klemens Franz, Rex Lee, Jolanta Lendzioszek, Gru Tsow',
    gameDesigners: 'Uwe Rosenberg',
    gameImageName: 'patchwork',
    gamePublisher: 'Lookout Games',
    yearPublished: '2014',
  },
  'Radlands': {
    gameArtists: 'Lina Cossette, Damien Mammoliti, Manny Trembley',
    gameDesigners: 'Daniel Piechnick',
    gameImageName: 'radlands',
    gamePublisher: 'Roxley',
    yearPublished: '2021',
  },
  'Raiders of the North Sea': {
    gameArtists: 'Mihajlo Dimitrievski',
    gameDesigners: 'Shem Phillips',
    gameImageName: 'raiders-of-the-north-sea',
    gamePublisher: 'Garphill Games',
    yearPublished: '2015',
  },
  'Raiders of Scythia': {
    gameArtists: 'Shem Phillips',
    gameDesigners: 'Shem Phillips',
    gameImageName: 'raiders-of-scythia',
    gamePublisher: 'Garphill Games',
    yearPublished: '2020',
  },
  'Railways of the World': {
    gameArtists: 'Kurt Miller, Paul Niemeyer, David Oram',
    gameDesigners: 'Glenn Drover, Martin Wallace',
    gameImageName: 'railway-of-the-world',
    gamePublisher: 'Eagle-Gryphon Games, Winsome Games',
    yearPublished: '2005',
  },
  'Raptor': {
    gameArtists: 'Vincent Dutrait',
    gameDesigners: 'Bruno Cathala, Bruno Faidutti',
    gameImageName: 'raptor',
    gamePublisher: 'Matagot',
    yearPublished: '2015',
  },
  'Resist!': {
    gameArtists: 'Albert Monteys',
    gameDesigners: 'Trevor Benjamin, Roger Tankersley, David Thompson',
    gameImageName: 'resist',
    gamePublisher: 'Salt & Pepper Games',
    yearPublished: '2022',
  },
  'Shadows of Malice': {
    gameArtists: 'Jim Felli',
    gameDesigners: 'Jim Felli',
    gameImageName: 'shadows-of-malice',
    gamePublisher: 'Devious Weasel Games',
    yearPublished: '2014',
  },
  'Shards of Infinity': {
    gameArtists: 'Aaron Nakahara',
    gameDesigners: 'Gary Arant, Justin Gary',
    gameImageName: 'shards-of-infinity',
    gamePublisher: 'Stone Blade Entertainment, Ultra PRO',
    yearPublished: '2018',
  },
  'Sniper Elite: The Board Game': {
    gameArtists: 'Jose David Lanza Cebrian, Edouard Grould, Ed Savage',
    gameDesigners: 'Roger Tankersley, David Thompson',
    gameImageName: 'sniper-elite-the-board-game',
    gamePublisher: 'Rebellion Unplugged',
    yearPublished: '2022',
  },
  'Sobek: 2 Players': {
    gameArtists: 'Xavier Gueniffey Durin',
    gameDesigners: 'Bruno Cathala, Sébastien Pauchon',
    gameImageName: 'sobek-2-players',
    gamePublisher: 'Catch Up Games',
    yearPublished: '2021',
  },
  'Spirit Island': {
    gameArtists: 'Jason Behnke, Loïc Berger, Loïc Billiau, Kat G Birmelin, Cari Corene, Lucas Durham, Rocky Hammer, Sydni Kruger, Nolan Nasser, Jorge Ramos, Adam Rebottaro, Moro Rogers, Graham Sternberg, Shane Tyree, Joshua Wright (I)',
    gameDesigners: 'R. Eric Reuss',
    gameImageName: 'spirit-island',
    gamePublisher: 'Greater Than Games, LLC',
    yearPublished: '2017',
  },
  'Space Alert': {
    gameArtists: 'Radim Pech, Milan Vavroň',
    gameDesigners: 'Vlaada Chvátil',
    gameImageName: 'space-alert',
    gamePublisher: 'Czech Games Edition',
    yearPublished: '2008',
  },
  'Splendor Duel': {
    gameArtists: 'Davide Tosello',
    gameDesigners: 'Marc André, Bruno Cathala',
    gameImageName: 'splendor-duel',
    gamePublisher: 'Space Cowboys',
    yearPublished: '2022',
  },
  'Steam': {
    gameArtists: 'John Austin, Jared Blando, Craig Hamilton, Christopher Moeller',
    gameDesigners: 'Martin Wallace',
    gameImageName: 'steam',
    gamePublisher: 'Mayfair Games',
    yearPublished: '2009',
  },
  'A Study in Emerald': {
    gameArtists: 'Geof Banyard, Peter Dennis, Anne Stokes',
    gameDesigners: 'Martin Wallace',
    gameImageName: 'study-in-emerald',
    gamePublisher: 'Treefrog Games',
    yearPublished: '2013',
  },
  'Summoner Wars: Master Set': {
    gameArtists: 'JJ Ariosa, Gary Simpson',
    gameDesigners: 'Colby Dauch',
    gameImageName: 'summoner-wars',
    gamePublisher: 'Plaid Hat Games',
    yearPublished: '2011',
  },
  'Switch & Signal': {
    gameArtists: 'Claus Stephan, Antje Stephan',
    gameDesigners: 'David Thompson',
    gameImageName: 'switch-signal',
    gamePublisher: 'KOSMOS',
    yearPublished: '2020',
  },
  'Targi': {
    gameArtists: 'Taira Akitsu, Franz Vohwinkel',
    gameDesigners: 'Andreas Steiger',
    gameImageName: 'targi',
    gamePublisher: 'KOSMOS',
    yearPublished: '2012',
  },
  'That Time You Killed Me': {
    gameArtists: 'Jor Ros',
    gameDesigners: 'Peter C. Hayward',
    gameImageName: 'that-time-you-killed-me',
    gamePublisher: 'Pandasaurus Games',
    yearPublished: '2021',
  },
  'Through the Ages: A New Story of Civilization': {
    gameArtists: 'Filip Murmak, Radim Pech, Jakub Politzer, Milan Vavroň',
    gameDesigners: 'Vlaada Chvátil',
    gameImageName: 'through-ages-new-story-civilization',
    gamePublisher: 'Czech Games Edition',
    yearPublished: '2015',
  },
  'Undaunted: Stalingrad': {
    gameArtists: 'Roland MacDonald',
    gameDesigners: 'Trevor Benjamin, David Thompson',
    gameImageName: 'undaunted-stalingrad',
    gamePublisher: 'Osprey Games',
    yearPublished: '2022',
  },
  'Viscounts of the West Kingdom': {
    gameArtists: 'Mihajlo Dimitrievski',
    gameDesigners: 'S J Macdonald, Shem Phillips',
    gameImageName: 'viscounts-of-the-west-kingdom',
    gamePublisher: 'Garphill Games',
    yearPublished: '2020',
  },
  'War Chest': {
    gameArtists: 'Brigette Indelicato',
    gameDesigners: 'Trevor Benjamin, David Thompson',
    gameImageName: 'war-chest',
    gamePublisher: 'Alderac Entertainment Group',
    yearPublished: '2018',
  },
  'Watergate': {
    gameArtists: 'Klemens Franz, Viktor Kobilke',
    gameDesigners: 'Matthias Cramer',
    gameImageName: 'watergate',
    gamePublisher: 'Capstone Games',
    yearPublished: '2019',
  },
  'Wayfarers of the South Tigris': {
    gameArtists: 'Mihajlo Dimitrievski',
    gameDesigners: 'S J Macdonald, Shem Phillips',
    gameImageName: 'wayfarers-of-the-south-tigris',
    gamePublisher: 'Garphill Games',
    yearPublished: '2022',
  },
  'Zimby Mojo': {
    gameArtists: 'Jim Felli, Tani Pettit, Naomi Robinson',
    gameDesigners: 'Jim Felli',
    gameImageName: 'zimby-mojo',
    gamePublisher: 'Devious Weasel Games',
    yearPublished: '2016',
  },
}

export default gamesList;
