import Head from 'next/head'
import Image from 'next/image'

import { Flex, Heading, HStack, Spacer, VStack } from '@chakra-ui/react'
import { TopListItem } from '@/components/elements/TopListItem'
import { chrisList } from './api/listData/fav2Players2026/chrisList'
import { ryansList } from './api/listData/fav2Players2026/ryansList'
import { DefaultLayout } from '@/components/layouts/Default'



export default function Fav2Player2026() {
  return (
    <>
      <Head>
        <title>Tabletop Express Top List: Favorite 2 Player Only Games</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DefaultLayout
        bgPosition="center"
        bgSize="cover"
        bgBlendMode="multiply"
        pageTitle="Top 2 Player Only Games"
        width="100%"
      >
        <Flex flex={1} maxHeight="calc(100vh - 92px)">
            <VStack
              bg="blue.600"
              css={{
                '&::-webkit-scrollbar': {
                  display: 'none'
                }
              }}
              overflow="auto"
              p={4}
              width="100%"
            >
              {Object.entries(chrisList).map(([gameName, gameInfo]) => (
                <TopListItem
                  key={gameName}
                  colorScheme="blue"
                  gameArtists={gameInfo.gameArtists}
                  gameDesigners={gameInfo.gameDesigners}
                  gameImageName={gameInfo.gameImageName}
                  gameName={gameName}
                  gamePublisher={gameInfo.gamePublisher}
                  sequence={gameInfo.sequence}
                  title="Chris' Pick"
                  yearPublished={gameInfo.yearPublished}
                />
              ))}
            </VStack>
          <VStack
            bg="red.600"
            css={{
              '&::-webkit-scrollbar': {
                display: 'none'
              }
            }}
            overflow="auto"
            p={4}
            width="100%"
          >
            {Object.entries(ryansList).map(([gameName, gameInfo]) => (
              <TopListItem
                key={gameName}
                colorScheme="red"
                gameArtists={gameInfo.gameArtists}
                gameDesigners={gameInfo.gameDesigners}
                gameImageName={gameInfo.gameImageName}
                gameName={gameName}
                gamePublisher={gameInfo.gamePublisher}
                sequence={gameInfo.sequence}
                title="Ryan's Pick"
                yearPublished={gameInfo.yearPublished}
              />
            ))}
          </VStack>
        </Flex>
      </DefaultLayout>
    </>
  )
}
