import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import { Flex, Heading, HStack, Spacer, VStack } from '@chakra-ui/react'
import { TopListItem } from '@/components/elements/TopListItem'
import { anthonysList } from './api/listData/fav2022/anthonysList'
import { DefaultLayout } from '@/components/layouts/Default'
import { ryansList } from './api/listData/fav2022/ryansList'
import { chrisList } from './api/listData/fav2022/chrisList'
import { gamesList } from './api/gameData'

const inter = Inter({ subsets: ['latin'] })

export default function Fav2022() {
  return (
    <>
      <Head>
        <title>Tabletop Express Top List: Favorite 2022 Games</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DefaultLayout pageTitle="Favorite 2022 Games">
        <Flex
          bg="blue.600"
          css={{
            '&::-webkit-scrollbar': {
              display: 'none'
            }
          }}
          flexDirection="column"
          gap={2}
          overflow="auto"
          p={4}
          width="100%"
        >
          {Object.entries(chrisList).map(([gameName, gameInfo]) => (
            <TopListItem
              key={gameName}
              badgeText={gameInfo.badgeText}
              colorScheme="blue"
              crossover={gameInfo.crossover}
              gameArtists={gameInfo.gameArtists}
              gameDesigners={gameInfo.gameDesigners}
              gameImageName={gameInfo.gameImageName}
              gameName={gameName}
              gamePublisher={gameInfo.gamePublisher}
              height="fit-content"
              sequence={gameInfo.sequence}
              title="Chris' Pick"
              yearPublished={gameInfo.yearPublished}
              width="100%"
              order={gameInfo.sequence}
            />
          ))}
          <TopListItem
            colorScheme="blue"
            gameArtists={gamesList['Agricola'].gameArtists}
            gameDesigners={gamesList['Agricola'].gameDesigners}
            gameImageName={gamesList['Agricola'].gameImageName}
            gameName="Agricola"
            gamePublisher={gamesList['Agricola'].gamePublisher}
            height="fit-content"
            title="Chris' Pick (Favorite New to Me)"
            yearPublished={gamesList['Agricola'].yearPublished}
            width="100%"
            order={11}
          />
          <TopListItem
            colorScheme="blue"
            gameArtists={gamesList['Star Wars: Outer Rim – Unfinished Business'].gameArtists}
            gameDesigners={gamesList['Star Wars: Outer Rim – Unfinished Business'].gameDesigners}
            gameImageName={gamesList['Star Wars: Outer Rim – Unfinished Business'].gameImageName}
            gameName="Star Wars: Outer Rim – Unfinished Business"
            gamePublisher={gamesList['Star Wars: Outer Rim – Unfinished Business'].gamePublisher}
            height="fit-content"
            title="Chris' Pick (Favorite Expansion)"
            yearPublished={gamesList['Star Wars: Outer Rim – Unfinished Business'].yearPublished}
            width="100%"
            order={12}
          />
        </Flex>
        <Flex
          bg="red.600"
          css={{
            '&::-webkit-scrollbar': {
              display: 'none'
            }
          }}
          flexDirection="column"
          gap={2}
          overflow="auto"
          p={4}
          width="100%"
        >
          {Object.entries(ryansList).map(([gameName, gameInfo]) => (
            <TopListItem
              key={gameName}
              badgeText={gameInfo.badgeText}
              colorScheme="red"
              crossover={gameInfo.crossover}
              gameArtists={gameInfo.gameArtists}
              gameDesigners={gameInfo.gameDesigners}
              gameImageName={gameInfo.gameImageName}
              gameName={gameName}
              gamePublisher={gameInfo.gamePublisher}
              height="fit-content"
              sequence={gameInfo.sequence}
              title="Ryan's Pick"
              yearPublished={gameInfo.yearPublished}
              width="100%"
              order={gameInfo.sequence}
            />
          ))}
          <TopListItem
            colorScheme="red"
            gameArtists={gamesList['Barrage'].gameArtists}
            gameDesigners={gamesList['Barrage'].gameDesigners}
            gameImageName={gamesList['Barrage'].gameImageName}
            gameName="Barrage"
            gamePublisher={gamesList['Barrage'].gamePublisher}
            height="fit-content"
            title="Ryan's Pick (Favorite New to Me)"
            yearPublished={gamesList['Barrage'].yearPublished}
            width="100%"
            order={11}
          />
          <TopListItem
            colorScheme="red"
            gameArtists={gamesList['G.I. Joe Deck-Building Game: Shadow of the Serpent Expansion'].gameArtists}
            gameDesigners={gamesList['G.I. Joe Deck-Building Game: Shadow of the Serpent Expansion'].gameDesigners}
            gameImageName={gamesList['G.I. Joe Deck-Building Game: Shadow of the Serpent Expansion'].gameImageName}
            gameName="G.I. Joe Deck-Building Game: Shadow of the Serpent Expansion"
            gamePublisher={gamesList['G.I. Joe Deck-Building Game: Shadow of the Serpent Expansion'].gamePublisher}
            height="fit-content"
            title="Ryan's Pick (Favorite Expansion)"
            yearPublished={gamesList['G.I. Joe Deck-Building Game: Shadow of the Serpent Expansion'].yearPublished}
            width="100%"
            order={12}
          />
        </Flex>
        <Flex
          bg="purple.600"
          css={{
            '&::-webkit-scrollbar': {
              display: 'none'
            }
          }}
          flexDirection="column"
          gap={2}
          overflow="auto"
          p={4}
          width="100%"
        >
          {Object.entries(anthonysList).map(([gameName, gameInfo]) => (
            <TopListItem
              key={gameName}
              badgeText={gameInfo.badgeText}
              colorScheme="purple"
              crossover={gameInfo.crossover}
              gameArtists={gameInfo.gameArtists}
              gameDesigners={gameInfo.gameDesigners}
              gameImageName={gameInfo.gameImageName}
              gameName={gameName}
              gamePublisher={gameInfo.gamePublisher}
              height="fit-content"
              sequence={gameInfo.sequence}
              title="Anthony's Pick"
              yearPublished={gameInfo.yearPublished}
              width="100%"
              order={gameInfo.sequence}
            />
          ))}
        </Flex>
      </DefaultLayout>
    </>
  )
}
