import Head from 'next/head'
import Image from 'next/image'

import { Flex, Heading, HStack, Spacer, VStack } from '@chakra-ui/react'
import { TopListItem } from '@/components/elements/TopListItem'
import { chrisList } from './api/listData/fav2Players2024/chrisList'
import { ryansList } from './api/listData/fav2Players2024/ryansList'
import { anthonysList } from './api/listData/fav2Players2024/anthonysList'



export default function Fav2Player2023() {
  return (
    <>
      <Head>
        <title>Tabletop Express Top List: Favorite 2 Player Only Games</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex flexDirection="column" height="100vh" width="100vw">
        <HStack bg="white" p={4}>
          <Image alt="Tabletop Express Logo" src="/ttexpress-circle-logo.png" height={60} width={60} />
          <Heading>Tabletop Express</Heading>
          <Spacer />
          <Heading>Favorite 2 Player Only Games</Heading>
        </HStack>
        <Flex flex={1} maxHeight="calc(100vh - 92px)">
            <VStack
              bg="blue.600"
              css={{
                '&::-webkit-scrollbar': {
                  display: 'none'
                }
              }}
              overflow="auto"
              p={4}
              width="100%"
            >
              {Object.entries(chrisList).map(([gameName, gameInfo]) => (
                <TopListItem
                  key={gameName}
                  colorScheme="blue"
                  gameArtists={gameInfo.gameArtists}
                  gameDesigners={gameInfo.gameDesigners}
                  gameImageName={gameInfo.gameImageName}
                  gameName={gameName}
                  gamePublisher={gameInfo.gamePublisher}
                  sequence={gameInfo.sequence}
                  title="Chris' Pick"
                  yearPublished={gameInfo.yearPublished}
                />
              ))}
            </VStack>
          <VStack
            bg="red.600"
            css={{
              '&::-webkit-scrollbar': {
                display: 'none'
              }
            }}
            overflow="auto"
            p={4}
            width="100%"
          >
            {Object.entries(ryansList).map(([gameName, gameInfo]) => (
              <TopListItem
                key={gameName}
                colorScheme="red"
                gameArtists={gameInfo.gameArtists}
                gameDesigners={gameInfo.gameDesigners}
                gameImageName={gameInfo.gameImageName}
                gameName={gameName}
                gamePublisher={gameInfo.gamePublisher}
                sequence={gameInfo.sequence}
                title="Ryan's Pick"
                yearPublished={gameInfo.yearPublished}
              />
            ))}
          </VStack>
          <VStack
            bg="purple.600"
            css={{
              '&::-webkit-scrollbar': {
                display: 'none'
              }
            }}
            overflow="auto"
            p={4}
            width="100%"
          >
          {Object.entries(anthonysList).map(([gameName, gameInfo]) => (
            <TopListItem
              key={gameName}
              colorScheme="purple"
              gameArtists={gameInfo.gameArtists}
              gameDesigners={gameInfo.gameDesigners}
              gameImageName={gameInfo.gameImageName}
              gameName={gameName}
              gamePublisher={gameInfo.gamePublisher}
              imageBoxExtension={gameInfo.imageBoxExtension}
              imageExtension={gameInfo.imageExtension}
              sequence={gameInfo.sequence}
              title="Anthony's Pick"
              yearPublished={gameInfo.yearPublished}
            />
          ))}
          </VStack>
        </Flex>
      </Flex>
    </>
  )
}
