import Head from 'next/head'
import Image from 'next/image'

import { Flex, Heading, HStack, Spacer, VStack } from '@chakra-ui/react'
import { TopListItem } from '@/components/elements/TopListItem'
import { chrisList } from './api/listData/favDesigners/chrisList'
import { anthonysList } from './api/listData/favDesigners/anthonysList'
import { ryansList } from './api/listData/favDesigners/ryansList'
import { DefaultLayout } from '@/components/layouts/Default'



export default function FavDesigners2023() {
  return (
    <>
      <Head>
        <title>Tabletop Express Top List: Favorite Designers</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DefaultLayout pageTitle="Favorite Designers">
        <VStack
          bg="blue.600"
          css={{
            '&::-webkit-scrollbar': {
              display: 'none'
            }
          }}
          overflow="auto"
          p={4}
          width="100%"
        >
          {Object.entries(chrisList).map(([personName, personInfo]) => (
            <TopListItem
              key={personName}
              colorScheme="blue"
              games={personInfo.games}
              itemType="person"
              personName={personName}
              personImageName={personInfo.personImageName}
              sequence={personInfo.sequence}
              title="Chris' Pick"
            />
          ))}
        </VStack>
        <VStack
          bg="red.600"
          css={{
            '&::-webkit-scrollbar': {
              display: 'none'
            }
          }}
          overflow="auto"
          p={4}
          width="100%"
        >
          {Object.entries(ryansList).map(([personName, personInfo]) => (
            <TopListItem
              key={personName}
              colorScheme="red"
              games={personInfo.games}
              itemType="person"
              personName={personName}
              personImageName={personInfo.personImageName}
              sequence={personInfo.sequence}
              title="Ryan's Pick"
            />
          ))}
        </VStack>
          <VStack
            bg="purple.600"
            css={{
              '&::-webkit-scrollbar': {
                display: 'none'
              }
            }}
            overflow="auto"
            p={4}
            width="100%"
          >
          {Object.entries(anthonysList).map(([personName, personInfo]) => (
            <TopListItem
              key={personName}
              colorScheme="purple"
              games={personInfo.games}
              itemType="person"
              personName={personName}
              personImageName={personInfo.personImageName}
              sequence={personInfo.sequence}
              title="Anthony's Pick"
            />
          ))}
        </VStack>
      </DefaultLayout>
    </>
  )
}
