import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import { Flex, Heading, HStack, Spacer, VStack } from '@chakra-ui/react'
import { TopListItem } from '@/components/TopListItem'
import { chrisList } from './api/favDesigners/chrisList'
import { anthonysList } from './api/favDesigners/anthonysList'
import { ryansList } from './api/favDesigners/ryansList'

const inter = Inter({ subsets: ['latin'] })

export default function FavDesigners() {
  return (
    <>
      <Head>
        <title>Tabletop Express Top List</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex flexDirection="column" height="100vh" width="100vw">
        <HStack bg="white" p={4}>
          <Image alt="Tabletop Express Logo" src="/ttexpress-circle-logo.png" height={60} width={60} />
          <Heading>Tabletop Express</Heading>
          <Spacer />
          <Heading>Favorite Designers</Heading>
        </HStack>
        <Flex flex={1} maxHeight="calc(100vh - 92px)">
            <VStack
              bg="blue.600"
              css={{
                '&::-webkit-scrollbar': {
                  display: 'none'
                }
              }}
              overflow="auto"
              p={4}
              width="100%"
            >
              {Object.entries(chrisList).map(([personName, personInfo]) => (
                <TopListItem
                  key={personName}
                  colorScheme="blue"
                  games={personInfo.games}
                  itemType="person"
                  personName={personName}
                  personImageName={personInfo.personImageName}
                  sequence={personInfo.sequence}
                  title="Chris' Pick"
                />
              ))}
            </VStack>
          <VStack
            bg="red.600"
            css={{
              '&::-webkit-scrollbar': {
                display: 'none'
              }
            }}
            overflow="auto"
            p={4}
            width="100%"
          >
            {Object.entries(ryansList).map(([personName, personInfo]) => (
              <TopListItem
                key={personName}
                colorScheme="red"
                games={personInfo.games}
                itemType="person"
                personName={personName}
                personImageName={personInfo.personImageName}
                sequence={personInfo.sequence}
                title="Ryan's Pick"
              />
            ))}
          </VStack>
          <VStack
            bg="purple.600"
            css={{
              '&::-webkit-scrollbar': {
                display: 'none'
              }
            }}
            overflow="auto"
            p={4}
            width="100%"
          >
          {Object.entries(anthonysList).map(([personName, personInfo]) => (
            <TopListItem
              key={personName}
              colorScheme="purple"
              games={personInfo.games}
              itemType="person"
              personName={personName}
              personImageName={personInfo.personImageName}
              sequence={personInfo.sequence}
              title="Anthony's Pick"
            />
          ))}
          </VStack>
        </Flex>
      </Flex>
    </>
  )
}
