import Head from 'next/head'
import { Inter } from '@next/font/google'
import { Card, CardBody, CardHeader, Container, Flex, Heading, Link as ChakraLink, List, ListItem, UnorderedList } from '@chakra-ui/react'
import { DefaultLayout } from '@/components/layouts/Default'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Tabletop Express Top List</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DefaultLayout pageTitle="Directory">
        <Container maxWidth="container.xl" my={4}>
          <Flex flexWrap="wrap" gap={4}>
            <Card>
              <CardHeader>
                <Heading>Call Aboard 2023</Heading>
              </CardHeader>
              <CardBody>
                <UnorderedList>
                  <ListItem>
                    <ChakraLink as={Link} href="/fav2PlayerGames2023">Favorite 2 Player Games 2023</ChakraLink>
                  </ListItem>
                  <ListItem>
                    <ChakraLink as={Link} href="/favDesigners2023">Favorite Designers 2023</ChakraLink>
                  </ListItem>
                </UnorderedList>
              </CardBody>
            </Card>
            <Card>
              <CardHeader>
                <Heading>Favorite Lists 2023</Heading>
              </CardHeader>
              <CardBody>
                <UnorderedList>
                  <ListItem>
                    <ChakraLink as={Link} href="/fav2PlayerGames2023">Favorite 2 Player Games 2023</ChakraLink>
                  </ListItem>
                  <ListItem>
                    <ChakraLink as={Link} href="/favDesigners2023">Favorite Designers 2023</ChakraLink>
                  </ListItem>
                </UnorderedList>
              </CardBody>
            </Card>
            <Card>
              <CardHeader>
                <Heading>Top Lists 2023</Heading>
              </CardHeader>
              <CardBody>
                <UnorderedList>
                  <ListItem>
                    <ChakraLink as={Link} href="/top20Chris2023">Chris Barrows</ChakraLink>
                  </ListItem>
                </UnorderedList>
              </CardBody>
            </Card>
          </Flex>
          <Heading>

          </Heading>
        </Container>
      </DefaultLayout>
    </>
  )
}
