import Head from 'next/head'

import { Avatar, Box, HStack, Image, SimpleGrid, theme, useBoolean } from '@chakra-ui/react'
import { TopListItem } from '@/components/elements/TopListItem'
import { DefaultLayout } from '@/components/layouts/Default'
import { transparentize } from 'polished'
import { dansList } from './api/listData/top202026/dansList'
import { tylersList } from './api/listData/top202026/tylersList'



export default function Top20DanTyler2026() {
  const [sort, setSort] = useBoolean()
  return (
    <>
      <Head>
        <title>Tabletop Express Top List: Dan &amp; Tyler&apos;s Top 20</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DefaultLayout
        bgImage="./backgroundImages/tyler-shelfie-2026.webp"
        bgPosition="center"
        bgSize="cover"
        pageTitle={(
          <HStack>
            <Avatar
              name="Dan"
              src="./personImages/dan-2026.webp"
            />
            <Avatar
              name="Tyler"
              src="./personImages/tyler-2026.webp"
            />
            <span>Dan &amp;</span>
            <span>Tyler&apos;s</span>
            <Image alt="Tabletop Express Top 20 logo" cursor="pointer" src="./top-20-logo.png" height={12} onClick={setSort.toggle} />
          </HStack>
        )}
        width="100%"
      >
        <SimpleGrid columns={[1, null, 2, null, 3, 4]} overflow="auto" width="100%">
          {Object.entries(dansList).map(([gameName, gameInfo]) => (
            <Box
              bgColor={transparentize(0.2, theme.colors.green[600])}
              key={gameName}
              order={gameInfo.sequence ? gameInfo.sequence * (sort ? -1 : 1) : 1}
              p={2}
              width="auto"
            >
              <TopListItem
                _open={{
                  height: '100%'
                }}
                badgeText={gameInfo.badgeText}
                colorScheme="green"
                crossover={gameInfo.crossover}
                gameArtists={gameInfo.gameArtists}
                gameDesigners={gameInfo.gameDesigners}
                gameImageName={gameInfo.gameImageName}
                gameName={gameName}
                gamePublisher={gameInfo.gamePublisher}
                sequence={gameInfo.sequence}
                title="Dan's Pick"
                yearPublished={gameInfo.yearPublished}
              />
            </Box>
          ))}
          {Object.entries(tylersList).map(([gameName, gameInfo]) => (
            <Box
              bgColor={transparentize(0.2, theme.colors.orange[600])}
              key={gameName}
              order={gameInfo.sequence ? gameInfo.sequence * (sort ? -1 : 1) : 1}
              p={2}
              width="auto"
            >
              <TopListItem
                key={gameName}
                _open={{
                  height: '100%'
                }}
                badgeText={gameInfo.badgeText}
                colorScheme="orange"
                crossover={gameInfo.crossover}
                gameArtists={gameInfo.gameArtists}
                gameDesigners={gameInfo.gameDesigners}
                gameImageName={gameInfo.gameImageName}
                gameName={gameName}
                gamePublisher={gameInfo.gamePublisher}
                sequence={gameInfo.sequence}
                title="Tyler's Pick"
                yearPublished={gameInfo.yearPublished}
              />
            </Box>
          ))}
        </SimpleGrid>
      </DefaultLayout>
    </>
  )
}
