import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import { Flex, Heading, HStack, SimpleGrid, Spacer, VStack } from '@chakra-ui/react'
import { TopListItem } from '@/components/elements/TopListItem'
import { DefaultLayout } from '@/components/layouts/Default'
import { chrisList } from './api/listData/fav2Players/chrisList'

const inter = Inter({ subsets: ['latin'] })

export default function FavDesigners2023() {
  return (
    <>
      <Head>
        <title>Tabletop Express Top List: Favorite Designers</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DefaultLayout pageTitle="Favorite Designers" p={4}>
        <Flex flexWrap="wrap" gap={4} width="100%" alignItems="flex-start">
          {Object.entries(chrisList).map(([gameName, gameInfo]) => (
            <TopListItem
              key={gameName}
              colorScheme="blue"
              gameArtists={gameInfo.gameArtists}
              gameDesigners={gameInfo.gameDesigners}
              gameImageName={gameInfo.gameImageName}
              gameName={gameName}
              gamePublisher={gameInfo.gamePublisher}
              height="fit-content"
              sequence={gameInfo.sequence}
              title="Chris' Pick"
              width="480px"
              yearPublished={gameInfo.yearPublished}
            />
          ))}
          </Flex>
      </DefaultLayout>
    </>
  )
}
