import Head from 'next/head'
import { Inter } from '@next/font/google'
import { SimpleGrid } from '@chakra-ui/react'
import { TopListItem } from '@/components/elements/TopListItem'
import { DefaultLayout } from '@/components/layouts/Default'
import { briansList } from './api/listData/top202023/briansList'

const inter = Inter({ subsets: ['latin'] })

export default function Top20Brian2023() {
  return (
    <>
      <Head>
        <title>Tabletop Express Top List: Brian&apos;s Top 20</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DefaultLayout bg="green.600" pageTitle="Brian's Top 20" width="100%">
        <SimpleGrid columns={[1, null, 2, null, 3, 4 ]} overflow="auto" p={4} spacing={4} width="100%">
          {Object.entries(briansList).map(([gameName, gameInfo]) => (
            <TopListItem
              key={gameName}
              colorScheme="green"
              gameArtists={gameInfo.gameArtists}
              gameDesigners={gameInfo.gameDesigners}
              gameImageName={gameInfo.gameImageName}
              gameName={gameName}
              gamePublisher={gameInfo.gamePublisher}
              height="fit-content"
              sequence={gameInfo.sequence}
              title="Brian's Pick"
              yearPublished={gameInfo.yearPublished}
              width="auto"
            />
          ))}
        </SimpleGrid>
      </DefaultLayout>
    </>
  )
}
