import Head from 'next/head'

import { Avatar, HStack, Image, SimpleGrid, useBoolean } from '@chakra-ui/react'
import { TopListItem } from '@/components/elements/TopListItem'
import { DefaultLayout } from '@/components/layouts/Default'
import { arwenList } from './api/listData/top202024/arwenList'



export default function Top20Arwen2024() {
  const [sort, setSort] = useBoolean()
  return (
    <>
      <Head>
        <title>Tabletop Express Top List: Arwen&apos;s Top 20</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DefaultLayout
        bgColor="purple.600"
        bgImage="./backgroundImages/arwen-shelfie.webp"
        bgPosition="center"
        bgSize="cover"
        bgBlendMode="multiply"
        pageTitle={(
          <HStack>
            <Avatar
              name="Arwen"
              src="./personImages/arwen.webp"
            />
            <span>Arwen&apos;s</span>
            <Image alt="Tabletop Express Top 20 logo" cursor="pointer" src="./top-20-logo.png" height={12} onClick={setSort.toggle} />
          </HStack>
        )}
        width="100%"
      >
        <SimpleGrid columns={[1, null, 2, null, 3, 4 ]} overflow="auto" p={4} spacing={4} width="100%">
          {Object.entries(arwenList).map(([gameName, gameInfo]) => (
            <TopListItem
              key={gameName}
              badgeText={gameInfo.badgeText}
              colorScheme="orange"
              crossover={gameInfo.crossover}
              gameArtists={gameInfo.gameArtists}
              gameDesigners={gameInfo.gameDesigners}
              gameImageName={gameInfo.gameImageName}
              gameName={gameName}
              gamePublisher={gameInfo.gamePublisher}
              height="fit-content"
              sequence={gameInfo.sequence}
              title="Arwen's Pick"
              yearPublished={gameInfo.yearPublished}
              width="auto"
              order={gameInfo.sequence ? gameInfo.sequence * (sort ? -1 : 1) : 1}
            />
          ))}
        </SimpleGrid>
      </DefaultLayout>
    </>
  )
}
