import Head from 'next/head'

import { Avatar, SimpleGrid } from '@chakra-ui/react'
import { TopListItem } from '@/components/elements/TopListItem'
import { DefaultLayout } from '@/components/layouts/Default'
import { daniellesList } from './api/listData/top202023/daniellesList'



export default function Top20Danielle2023() {
  return (
    <>
      <Head>
        <title>Tabletop Express Top List: Danielle&apos;s Top 20</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DefaultLayout
        bgColor="purple.600"
        bgImage="./backgroundImages/danielle-shelfie.webp"
        bgSize="cover"
        bgBlendMode="multiply"
        pageTitle={(
          <>
            <Avatar
              mr={2}
              name="Danielle"
              src="./personImages/danielle.webp"
            />
            Danielle&apos;s Top 20
          </>
        )}
        width="100%"
      >
        <SimpleGrid columns={[1, null, 2, null, 3, 4 ]} overflow="auto" p={4} spacing={4} width="100%">
          {Object.entries(daniellesList).map(([gameName, gameInfo]) => (
            <TopListItem
              key={gameName}
              badgeText={gameInfo.badgeText}
              colorScheme="purple"
              crossover={gameInfo.crossover}
              gameArtists={gameInfo.gameArtists}
              gameDesigners={gameInfo.gameDesigners}
              gameImageName={gameInfo.gameImageName}
              gameName={gameName}
              gamePublisher={gameInfo.gamePublisher}
              height="fit-content"
              sequence={gameInfo.sequence}
              title="Danielle's Pick"
              yearPublished={gameInfo.yearPublished}
              width="auto"
            />
          ))}
        </SimpleGrid>
      </DefaultLayout>
    </>
  )
}
