import Head from 'next/head'
import { Inter } from '@next/font/google'
import { Avatar, SimpleGrid } from '@chakra-ui/react'
import { TopListItem } from '@/components/elements/TopListItem'
import { DefaultLayout } from '@/components/layouts/Default'
import { chrisList } from './api/listData/top202023/chrisList'

const inter = Inter({ subsets: ['latin'] })

export default function Top20Chris2023() {
  return (
    <>
      <Head>
        <title>Tabletop Express Top List: Chris&apos; Top 20</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DefaultLayout
        bgColor="blue.600"
        bgImage="./backgroundImages/chris-shelfie.webp"
        bgSize="cover"
        bgBlendMode="multiply"
        pageTitle={(
          <>
            <Avatar
              mr={2}
              name="Chris Barrows"
              src="./personImages/chris-barrows.webp"
            />
            Chris&apos; Top 20
          </>
        )}
        width="100%"
      >
        <SimpleGrid columns={[1, null, 2, null, 3, 4 ]} overflow="auto" p={4} spacing={4} width="100%">
          {Object.entries(chrisList).map(([gameName, gameInfo]) => (
            <TopListItem
              key={gameName}
              badgeText={gameInfo.badgeText}
              colorScheme="blue"
              crossover={gameInfo.crossover}
              gameArtists={gameInfo.gameArtists}
              gameDesigners={gameInfo.gameDesigners}
              gameImageName={gameInfo.gameImageName}
              gameName={gameName}
              gamePublisher={gameInfo.gamePublisher}
              height="fit-content"
              sequence={gameInfo.sequence}
              title="Chris' Pick"
              yearPublished={gameInfo.yearPublished}
              width="auto"
            />
          ))}
        </SimpleGrid>
      </DefaultLayout>
    </>
  )
}
