import Head from 'next/head'

import { Avatar, Box, HStack, Image, SimpleGrid, theme, useBoolean } from '@chakra-ui/react'
import { TopListItem } from '@/components/elements/TopListItem'
import { DefaultLayout } from '@/components/layouts/Default'
import { arwenList } from './api/listData/top202025/arwenList'
import { transparentize } from 'polished'
import { oliviasList } from './api/listData/top202025/oliviasList'



export default function Top20Arwen2024() {
  const [sort, setSort] = useBoolean()
  return (
    <>
      <Head>
        <title>Tabletop Express Top List: Arwen &amp; Olivia&apos;s Top 20</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DefaultLayout
        bgImage="./backgroundImages/arwen-olivia-shelfie.webp"
        bgPosition="center"
        bgSize="cover"
        pageTitle={(
          <HStack>
            <Avatar
              name="Arwen"
              src="./personImages/arwen-2025.webp"
            />
            <Avatar
              name="Olivia"
              src="./personImages/olivia-2025.webp"
            />
            <span>Arwen &amp;</span>
            <span>Olivia &apos;s</span>
            <Image alt="Tabletop Express Top 20 logo" cursor="pointer" src="./top-20-logo.png" height={12} onClick={setSort.toggle} />
          </HStack>
        )}
        width="100%"
      >
        <SimpleGrid columns={[1, null, 2, null, 3, 4 ]} overflow="auto" width="100%">
          {Object.entries(arwenList).map(([gameName, gameInfo]) => (
            <Box
              bgColor={transparentize(0.2, theme.colors.pink[600])}
              key={gameName}
              order={gameInfo.sequence ? gameInfo.sequence * (sort ? -1 : 1) : 1}
              p={2}
              width="auto"
            >
              <TopListItem
                _open={{
                  height: '100%'
                }}
                badgeText={gameInfo.badgeText}
                colorScheme="pink"
                crossover={gameInfo.crossover}
                gameArtists={gameInfo.gameArtists}
                gameDesigners={gameInfo.gameDesigners}
                gameImageName={gameInfo.gameImageName}
                gameName={gameName}
                gamePublisher={gameInfo.gamePublisher}
                sequence={gameInfo.sequence}
                title="Arwen's Pick"
                yearPublished={gameInfo.yearPublished}
              />
            </Box>
          ))}
          {Object.entries(oliviasList).map(([gameName, gameInfo]) => (
            <Box
              bgColor={transparentize(0.2, theme.colors.green[600])}
              bgBlendMode="multiply"
              key={gameName}
              order={gameInfo.sequence ? gameInfo.sequence * (sort ? -1 : 1) : 1}
              p={2}
              width="auto"
            >
              <TopListItem
                key={gameName}
                _open={{
                  height: '100%'
                }}
                badgeText={gameInfo.badgeText}
                colorScheme="green"
                crossover={gameInfo.crossover}
                gameArtists={gameInfo.gameArtists}
                gameDesigners={gameInfo.gameDesigners}
                gameImageName={gameInfo.gameImageName}
                gameName={gameName}
                gamePublisher={gameInfo.gamePublisher}
                sequence={gameInfo.sequence}
                title="Olivia's Pick"
                yearPublished={gameInfo.yearPublished}
              />
            </Box>
          ))}
        </SimpleGrid>
      </DefaultLayout>
    </>
  )
}
