import Head from 'next/head'

import { Avatar, HStack, Image, SimpleGrid, useBoolean } from '@chakra-ui/react'
import { TopListItem } from '@/components/elements/TopListItem'
import { DefaultLayout } from '@/components/layouts/Default'
import { chrisList } from './api/listData/top202024/chrisList'



export default function Top20Chris2024() {
  const [sort, setSort] = useBoolean()
  return (
    <>
      <Head>
        <title>Tabletop Express Top List: Chris&apos; Top 20</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DefaultLayout
        bgColor="blue.600"
        bgImage="./backgroundImages/chris-shelfie.webp"
        bgSize="cover"
        bgBlendMode="multiply"
        pageTitle={(
          <HStack>
            <Avatar
              name="Chris Barrows"
              src="./personImages/chris-barrows-2024.webp"
            />
            <span>Chris&apos;</span>
            <Image alt="Tabletop Express Top 20 logo" cursor="pointer" src="./top-20-logo.png" height={12} onClick={setSort.toggle} />
          </HStack>
        )}
        width="100%"
      >
        <SimpleGrid columns={[1, null, 2, null, 3, 4 ]} overflow="auto" p={4} spacing={4} width="100%">
          {Object.entries(chrisList).map(([gameName, gameInfo]) => (
            <TopListItem
              key={gameName}
              badgeText={gameInfo.badgeText}
              colorScheme="blue"
              crossover={gameInfo.crossover}
              gameArtists={gameInfo.gameArtists}
              gameDesigners={gameInfo.gameDesigners}
              gameImageName={gameInfo.gameImageName}
              gameName={gameName}
              gamePublisher={gameInfo.gamePublisher}
              height="fit-content"
              sequence={gameInfo.sequence}
              title="Chris' Pick"
              yearPublished={gameInfo.yearPublished}
              width="auto"
              order={gameInfo.sequence ? gameInfo.sequence * (sort ? -1 : 1) : 1}
            />
          ))}
        </SimpleGrid>
      </DefaultLayout>
    </>
  )
}
